CREATE DATABASE QUANLY_NHASACH
GO
USE QUANLY_NHASACH
GO



CREATE TABLE KHO
(
	MASACH VARCHAR(55) NOT NULL,
	TONGSOLUONG INT NOT NULL,
	SOLUONGCONLAI INT NOT NULL,
	PRIMARY KEY (MASACH),
)
CREATE TABLE NHATKINHAPSACH
(
	STT INT IDENTITY (1,1) NOT NULL,
	MASACH VARCHAR(55) NOT NULL,
	SOLUONG INT NOT NULL,
	NGAYNHAP DATE  NOT NULL,
	PRIMARY KEY (STT),
	FOREIGN KEY  (MASACH) REFERENCES KHO (MASACH)
)


CREATE TABLE TACGIA
(
	MATACGIA VARCHAR(55) NOT NULL,
	TENTACGIA VARCHAR(55) NOT NULL,
	NAMSINH DATE  NOT NULL,
	NAMMAT DATE  NOT NULL,
	PRIMARY KEY (MATACGIA),
)
CREATE TABLE LOAISACH
(
	MALOAISACH VARCHAR(55) NOT NULL,
	TENLOAISACH VARCHAR(55) NOT NULL,
	PRIMARY KEY (MALOAISACH),
)
CREATE TABLE LINHVUC
(
	MALINHVUC VARCHAR(55) NOT NULL,
	TENLINHVUC VARCHAR(55) NOT NULL,
	PRIMARY KEY (MALINHVUC),
)
CREATE TABLE SACHKHUYENMAI
(
	MASACH VARCHAR(55) NOT NULL,
	MUCGIAMGIA FLOAT NOT NULL,
	PRIMARY KEY (MASACH),
)

CREATE TABLE THONGTINXUATBAN
(
	MASACH VARCHAR(55) NOT NULL,
	NHATXUATBAN VARCHAR(55) NOT NULL,
	NAMXUATBAN DATE  NOT NULL,
	GIABIA FLOAT NOT NULL,
	GIANHAP FLOAT NOT NULL,
	PRIMARY KEY (MASACH),
)


CREATE TABLE HOADON
(
	MAHOADON INT  NOT NULL,
	NGAYTAO DATE  NOT NULL,
	TONGTIEN FLOAT NOT NULL,
	KHUYENMAI FLOAT NOT NULL,
	PRIMARY KEY (MAHOADON),
)
CREATE TABLE HOADONCHITIET
(
	MAHOADONCHITIET INT IDENTITY(1,1) NOT NULL,
	SOLUONG INT NOT NULL,
	NGAYTAO DATE  NOT NULL,
	TENSACH VARCHAR(55) NOT NULL,
	VAT FLOAT NOT NULL,
	MASACH VARCHAR(55) NOT NULL,
	MAHOADON INT NOT NULL,
	PRIMARY KEY (MAHOADONCHITIET),
	FOREIGN KEY  (MAHOADON) REFERENCES HOADON (MAHOADON),
)
CREATE TABLE KHACHHANG
(
	MAKHACHHANG VARCHAR(55) NOT NULL,
	TENKHACHHANG VARCHAR(55) NOT NULL,
	SODIENTHOAI VARCHAR(55) NOT NULL,
	EMAIL VARCHAR(55) NOT NULL,
	MAHOADONCHITIET INT NOT NULL,
	PRIMARY KEY (MAKHACHHANG),
	FOREIGN KEY  (MAHOADONCHITIET) REFERENCES HOADONCHITIET (MAHOADONCHITIET),
)



CREATE TABLE SACH

(
	MASACH VARCHAR(55) NOT NULL,
	TENSACH VARCHAR(55) NOT NULL,
	NHAXUATBAN VARCHAR(55) NOT NULL,
	MATACGIA VARCHAR(55) NOT NULL,
	TENTACGIA VARCHAR(55) NOT NULL,
	MALOAISACH VARCHAR(55) NOT NULL,
	MALINHVUC VARCHAR(55) NOT NULL,
	MAKHACHHANG VARCHAR(55) NOT NULL,
	ANH nVARCHAR(255) NOT NULL,
	NAMXUATBAN DATE  NOT NULL,
	SOLUONG INT NOT NULL,
	GIATIEN FLOAT NOT NULL,
	PRIMARY KEY (MASACH),
	FOREIGN KEY  (MASACH) REFERENCES KHO (MASACH),
	FOREIGN KEY  (MATACGIA) REFERENCES TACGIA (MATACGIA),
	FOREIGN KEY  (MALOAISACH) REFERENCES LOAISACH (MALOAISACH),
	FOREIGN KEY  (MALINHVUC) REFERENCES LINHVUC (MALINHVUC),
	FOREIGN KEY  (MAKHACHHANG) REFERENCES KHACHHANG (MAKHACHHANG),
	FOREIGN KEY  (MASACH) REFERENCES SACHKHUYENMAI (MASACH),
	FOREIGN KEY  (MASACH) REFERENCES THONGTINXUATBAN (MASACH),
)
insert into KHO(MASACH,SOLUONGCONLAI,TONGSOLUONG)
values ('MS1',1,10)
insert into NHATKINHAPSACH(MASACH,NGAYNHAP,SOLUONG)
values ('MS1','2024/04/01',2)
insert into TACGIA(MATACGIA,TENTACGIA,NAMSINH,NAMMAT)
values ('TG1',N'Tố Hữu','1996/05/04','1999/10/10')
insert into LINHVUC(MALINHVUC,TENLINHVUC)
values ('LV1',N'XÃ HỘI')
insert into LOAISACH(MALOAISACH,TENLOAISACH)
values ('LS1',N'THƠ')
insert into SACHKHUYENMAI(MASACH,MUCGIAMGIA)
values ('MS1',0.5)
insert into THONGTINXUATBAN(MASACH,NAMXUATBAN,NHATXUATBAN,GIANHAP,GIABIA)
values ('MS1','2002',N'KIM ĐỒNG',100000,50000)
insert into HOADON(MAHOADON,KHUYENMAI,NGAYTAO,TONGTIEN)
values (1,0.5,'2002/11/12',100000)
insert into HOADONCHITIET(MAHOADON,MASACH,NGAYTAO,SOLUONG,TENSACH,VAT)
values (1,'MS1','2000/10/10',10,N'KIM BÌNH MAI',0.5)
insert into KHACHHANG(MAKHACHHANG,MAHOADONCHITIET,TENKHACHHANG,SODIENTHOAI,EMAIL)
values ('MK1',1,N'TRẦN THÁI SƠN','0369852147','sonRAU@GMAIL.com')
insert into SACH(MASACH,MATACGIA,MALOAISACH,MALINHVUC,MAKHACHHANG,NAMXUATBAN,NHAXUATBAN,SOLUONG,TENSACH,TENTACGIA,GIATIEN,ANH)
values ('MS1','TG1','LS1','LV1','MK1','2002',N'KIM ĐỒNG',10,N'KIM BÌNH MAI',N'Tố Hữu',100000,'IMAGE.01')

SELECT * FROM SACH
SELECT * FROM KHO
SELECT * FROM NHATKINHAPSACH
SELECT * FROM TACGIA
SELECT * FROM LINHVUC
SELECT * FROM LOAISACH
SELECT * FROM HOADON
SELECT * FROM HOADONCHITIET
SELECT * FROM KHACHHANG
SELECT * FROM SACHKHUYENMAI
SELECT * FROM THONGTINXUATBAN